backend:
  name: test-repo
  branch: dev

media_folder: "assets"
public_folder: "./assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                default: "Welcome to Inochido"
              - label: "Subtitle"
                name: "subtitle"
                widget: "text"
                default: "Your path to holistic growth"
              - label: "Button Text"
                name: "buttonText"
                widget: "string"
                default: "Explore Our Pillars"